questions = [
    "Pertumbuhan sangat lambat?",
    "Apakah nafsu makan babi menurun?",
    "Apakah kulit babi tampak pucat?",
    "Apakah babi tampak lemas, lesu, atau tidak aktif?",
    "Apakah selaput lendir (gusi, mata, telinga) babi tampak pucat?",
    "Apakah babi mengalami pernapasan cepat?",
    "Apakah denyut jantung babi cepat (takikardia)?",
    "Apakah bulu babi terlihat kusam dan kasar?",
    "Apakah babi lebih senang tidur dari biasanya?",
    "Apakah kotoran yang dihasilkan babi berbentuk cairan?",
    "Apakah feses(kotoran) babi berlendir atau berdarah?",
    "Apakah perut babi kembung atau membesar?",
    "Apakah babi menunjukkan tanda dehidrasi seperti mata cekung atau kulit kering?",
    "Apakah kotoran babi sangat bau?",
    "Apakah babi mengalami penurunan berat badan yang cepat?",
    "Apakah terdapat cacing dalam feses(kotoran) babi?",
    "Apakah babi selalu merasa kesakitan?",
    "Apakah perut babi membuncit?",
    "Apakah anus babi bengkak dan berwarna kemerahan?",
    "Apakah babi menggaruk atau mengalami gatal-gatal sekujur tubuh?",
    "Apakah terdapat luka terbuka pada kulit babi?",
    "Apakah terdapat luka terbuka pada kulit babi?",
    "Apakah babi demam?",
    "Apakah babi kesulitan bernapas?",
    "Apakah babi nafsu makannya menurun lebih jauh?",
    "Apakah terdapat bintik-bintik kecil berwarna merah dan melepuh yang mengeluarkan cairan darah berwarna putih (nanah)?",
    "Apakah terlihat leleran dari mata dan hidung babi?",
    "Apakah ada luka atau melepuh di sekitar mulut, lidah, dan kuku babi?",
    "Apakah babi pincang atau mengalami nyeri pada kaki?",
    "Apakah terdapat vesikel (lepuh) di sekitar mulut atau hidung babi?",
    "Apakah produksi susu babi betina menurun?",
    "Apakah kuku babi terlepas?",
    "Apakah terjadi kematian mendadak pada babi?",
    "Apakah babi mengalami kejang atau gemetaran?",
    "Apakah babi demam sangat tinggi?",
    "Apakah babi mengalami batuk atau muntah?",
    "Apakah babi tampak jalan sempoyongan (ataxia)?",
    "Apakah babi mengalami kejang?",
    "Apakah mata babi merah dan berair?",
    "Apakah babi mengalami tremor tubuh (gemetar ringan)?",
    "Apakah terdapat lesi(ruam) pada kulit dan pendarahan pada kulit babi?",
    "Apakah terdapat pembesaran limpa dan kelenjar getah bening pada babi?",
    "Apakah babi tidak responsif terhadap rangsangan?",
    "Apakah terjadi penurunan suhu tubuh tiba-tiba menjelang kematian?",
    "Apakah terdapat pendarahan dari lubang hidung, mulut, atau anus babi?"
]
